### ISSUE TITLE
refreshing connectivity

### ISSUE THREAD

**Issue by lbrines** [siacentral/host-dashboard#10]
Hi, I have the following warning that I could not solve

host-dashboard_1_dda3953fcbe9 | 2020/07/20 12:05:27 sync.go:68: refreshing connectivity: failed to check connection: invalid character '<' looking for beginning of value

At https://siastats.info/hosts the node is online

**Comment by n8mgr** [comment]
Sorry for the inconvenience, Sia Central's host troubleshooter is currently offline. Working on getting all services back up and running as soon as possible.
