### ISSUE TITLE
Skynet registry disabled

### ISSUE THREAD

**Issue by lbrines** [siacentral/host-dashboard#11]
After updating to version 1.5.1 I have this message "Skynet registry disabled", how can I solve them, thank you very much

**Comment by n8mgr** [comment]
Skynet registry is a new type of storage for hosts. The registry, by default, is stored with your consensus and host data folders. Make sure you have enough free space. It's recommended to store it on an SSD as read/write speed is important, but not required.

If you're using Host Manager, update to v1.0.26 then on the Configuration page there is a new "Skynet" section. You can configure the size and location there.

If you're on cli you will need to run `siac host config registrysize 4GB` to start accepting Skynet registry data. If you're using Sia-UI you can run the command in the built in terminal `host config registrysize 4GB`. This will allocate 4GB of space on the same drive your consensus is stored for the Skynet registry. 

If you don't want to opt-in you can safely ignore the warning.

You can check if your host is setup using the host troubleshooter: https://troubleshoot.siacentral.com/.
