### ISSUE TITLE
Host timeout message stays permanently

### ISSUE THREAD

**Issue by mike76-dev** [siacentral/host-dashboard#28]
When a host times out, a red message appears. This message stays even after the host stops timing out (according to Sia Host Manager), until the dashboard is restarted.

**Comment by n8mgr** [comment]
Is it possible the timeout just hadn't corrected itself? It's possible for the test on Dashboard to fail while passing in HM. 

It looks like I'm clearing the alert here https://github.com/siacentral/sia-host-dashboard/blob/master/dashboard/sync/status.go#L105, then adding it back here https://github.com/siacentral/sia-host-dashboard/blob/master/dashboard/sync/status.go#L132

Can you check your log for the `refreshing connectivity:` prefix?

**Comment by mike76-dev** [comment]
There's nothing in my log about `refreshing connectivity`.
Attached is my log file after I started the Dashboard at 11:38am today.
At 12:54pm I refreshed manually, and it said the host timed out. HM reported OK.
[log.log](https://github.com/siacentral/sia-host-dashboard/files/7740740/log.log)

**Comment by n8mgr** [comment]
Cannot reproduce
