### ISSUE TITLE
Browser access disabled due to security vulnerability

### ISSUE THREAD

**Issue by aseelert** [siacentral/host-dashboard#29]
I'm running SIA/SCPrime within a docker container. Downloaded the dashboard executable into it (for testing)

I'm not able to communicate with the API

/sia-dashboard/dashboard -sia-api-addr localhost:4280

2022/01/13 10:31:40 daemon.go:40: Starting Host Dashboard v1.0.2
2022/01/13 10:31:40 daemon.go:40: Revision: 389b856 Build Time: Thu, 04 Nov 2021 05:54:59 CET
2022/01/13 10:31:40 daemon.go:40: Syncing Sia Data...
2022/01/13 10:31:40 sync.go:118: warn: unable to retrieve bandwidth: [failed to get reader response; GET request error; Browser access disabled due to security vulnerability. Use ScPrime-UI or spc.]
2022/01/13 10:31:40 daemon.go:127: error syncing data: refreshing contracts: get sia contracts: [failed to get reader response; GET request error; Browser access disabled due to security vulnerability. Use ScPrime-UI or spc.]

spd --disable-api-security -d /scp-data --api-addr :4280

sudo docker run \
    --detach \
    --restart unless-stopped \
    -v /volume1/crypto_docker_scprime/scprime_meta:/scp-data \
    -v /volume1/crypto_docker_scprime/sia-dashboard:/sia-dashboard \
    --publish 127.0.0.1:4280:4280 \
    --publish 4281:4281 \
    --publish 4282:4282 \
    --publish 4283:4283 \
    --publish 4285:4285 \
    --publish 8884:8884 \
    --label=com.centurylinklabs.watchtower.enable=false \
    --env SCPRIME_WALLET_PASSWORD="something" \
    --env SCPRIME_API_PASSWORD=something \
    --env SIA_WALLET_PASSWORD="something" \
    --env SIA_API_PASSWORD=something \
    --env TZ="Europe/Berlin" \
    --name scprime\
    --network="sia-network"\
    scprime/scprime

**Comment by aseelert** [comment]
A classic connect to API is working, so I guess it would be nice to have the possibility to add an option for the usage either for ScPrime-Agent or SiaAgent, as well reusing the SIA_API_PASSWORD=something / env SCPRIME_API_PASSWORD=something 

curl -A "ScPrime-Agent" --user "":something localhost:4280/host 
{"encrypted":true,"height":168580,"rescanning":false,"unlocked":true,...........}

curl -A "SiaAgent" --user "":something localhost:4280/host
{"message":"Browser access disabled due to security vulnerability. Use ScPrime-UI or spc."}

**Comment by n8mgr** [comment]
Sorry, but I cannot support SCPrime in my projects anymore; leadership asked me to leave the community because I was too involved with the original Sia project. I believe they also offer a web-based dashboard, but I haven't kept up with the project.
