### ISSUE TITLE
Change line graphs to stacked line graphs

### ISSUE THREAD

**Issue by DeflateAwning** [siacentral/host-dashboard#38]
The line graphs (showing made/potential income, and showing number of contracts expiring per month) would be better if the two series were stacked. Can you make this change?

**Comment by DeflateAwning** [comment]
Why is this request rejected? From a data visualization standpoint, the lines should be stacked because the two series contribute to a whole value; they don't each represent independent values. This is truly an obvious change.

**Comment by n8mgr** [comment]
I'm not planning on changing the graphs at this point. In my opinion, from a visual standpoint, the two stacked area graphs demonstrate the relationship best. The "Revenue" graph shows earned income with potential income stacked. The "Contracts" graph shows successful contracts stacked with failed and expiring. "# of expired contracts" does not necessarily correlate with revenue.

**Comment by DeflateAwning** [comment]
I think there's a small misunderstanding of what I'm requesting. I wasn't suggesting we combine the graphs, but rather that we convert each graph from a line graph to a stacked area graph.

Here's an example of what a stacked area graph looks like. Each series is added above the previous series in the y-axis.

![image](https://user-images.githubusercontent.com/11021263/173471068-17187369-9b9f-4bd2-bb6b-88a3639244c8.png)

**Comment by n8mgr** [comment]
There's definitely a miscommunication. As I said in my previous comment, Host Dashboard  **currently** has stacked area charts:
<img width="1187" alt="Screen Shot 2022-06-13 at 7 19 47 PM" src="https://user-images.githubusercontent.com/5544150/173474152-2be98717-0544-4dff-ae85-5af5a54c4fef.png">

The upper graph from your photo is not what Host Dashboard graphs should look like. If your graph looks like overlapping lines, please send a photo and I can look at fixing whatever bug is causing it.

**Comment by DeflateAwning** [comment]
Yeah you're definitely right, I'm not sure what I was thinking; my bad. Sorry to bother you! Thanks for all you do!
