### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by BouweCeunen** [siacentral/host-dashboard#5]
I'm getting this message regularly:

`2020/05/18 22:34:47 sync.go:68: refreshing connectivity: Get https://api.siacentral.com/v2/troubleshoot/sia.ceunen.io:9982: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Everything is working ok, I think siacentral api is sometimes slow to return a response, is it possible to increase timeout so these messages will go away?

**Comment by n8mgr** [comment]
I've been seeing this lately too, I'll be adding another server to the API to load balance and decrease load times soon. Been seeing a pretty large uptick in usage recently.

I've increased the timeout on the latest master branch if you want to pull `siacentral/host-dashboard` or rebuild your container
