### ISSUE TITLE
Invalid character '<'

### ISSUE THREAD

**Issue by BouweCeunen** [siacentral/host-dashboard#6]
Hi,

I'm seeing a lot of `2020/06/02 16:10:01 sync.go:68: refreshing connectivity: invalid character '<' looking for beginning of value` messages.

Everything is working though.

**Comment by n8mgr** [comment]
I've noticed this as well. There seems to be a disconnect between Cloudflare and the troubleshooting server frequently causing Cloudflare to consider the service offline and show these messages. I'm not really sure why it happens: the server is up, accessible, and health checks are passing.. 

I've been in contact with their support trying to debug it.. Hopefully it will be resolved soon, or I may just switch off Cloudflare..

**Comment by n8mgr** [comment]
I think we've found the culprit. It appears that the new SiaMux test is not enforcing the 10 second timeout my service allows for tests. A few misconfigured hosts are able to keep the request open for 5 minutes before the request is finally killed. This may be causing Cloudflare's health detection to fail momentarily even though parallel requests are succeeding.

I've pushed up some additional logging and a custom version of SiaMux forcing its internal timeout to 10 seconds. Will continue monitoring and leave this open for the time being. Please let me know if you continue seeing this error.

**Comment by BouweCeunen** [comment]
Will reopen when it occurs again, do not see it now 👍
